name: Tests

on: push

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Build project
        run: npm
      - name: Run tests
        run: npm test
